import { OrderStatus as GeneratedOrderStatus } from './generated'
import { OrderStatus } from '@/model/enums/orderStatus'

/**
 * Map to "convert" a value of the order status enum generated by graphql-codegen
 * to the corresponding value of the order status enum of the frontend.
 */
export const backendToFrontend = new Map<GeneratedOrderStatus, OrderStatus>([
    [GeneratedOrderStatus.Pending, OrderStatus.Pending],
    [GeneratedOrderStatus.Placed, OrderStatus.Placed],
    [GeneratedOrderStatus.Rejected, OrderStatus.Rejected],
])

/**
 * Map to "convert" a value of the order status enum of the frontend
 * the corresponding value of the order status enum generated by graphql-codegen.
 */
export const frontendToBackend = new Map<OrderStatus, GeneratedOrderStatus>([
    [OrderStatus.Pending, GeneratedOrderStatus.Pending],
    [OrderStatus.Placed, GeneratedOrderStatus.Placed],
    [OrderStatus.Rejected, GeneratedOrderStatus.Rejected],
])
