name: Build and Lint and Format

on: pull_request

jobs:
  job-1:
    name: Build and Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          check-latest: true
      - name: Enable corepack
        run: corepack enable
      - name: Set yarn version to berry
        run: yarn set version berry
      - name: Install Dependencies
        run: yarn
      - name: Build the Website
        run: yarn build
      - name: Run Linter
        run: yarn lint:check
      - name: Run Formatter
        run: yarn format:check
      - name: Disable corepack
        if: always()
        run: corepack disable
